version: '3.4'
services:
  uploader-plus-share:
    image: alfresco-share-uploader-plus:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../uploader-plus-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: uploader-plus-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  uploader-plus-acs:
    image: alfresco-content-services-uploader-plus:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../uploader-plus-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url=\"failover:(nio://uploader-plus-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - uploader-plus-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - uploader-plus-postgres
  uploader-plus-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - uploader-plus-db-volume:/var/lib/postgresql/data
  uploader-plus-ass:
#    image: alfresco/alfresco-search-services:2.0.3
    image: alfresco/alfresco-search-services:2.0.12 #this version has support for arm64, the one commented above does not despite coming as recommended.
    environment:
      SOLR_ALFRESCO_HOST: uploader-plus-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: uploader-plus-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - uploader-plus-ass-volume:/opt/alfresco-search-services/contentstore
      - uploader-plus-ass-volume:/opt/alfresco-search-services/data
  uploader-plus-activemq:
#      image: alfresco/alfresco-activemq:5.16.1
      image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  uploader-plus-acs-volume:
    external: true
  uploader-plus-db-volume:
    external: true
  uploader-plus-ass-volume:
    external: true
